musics = {"aadat se majboor": "https://www.youtube.com/watch?v=sB-S5LBU1eA",
        "palat tera hero idhar hai": "https://www.youtube.com/watch?v=9vkcYxbGdTE",
        "perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
        "love me not": "https://www.youtube.com/watch?v=cswfR85D7jM",
        "haareya": "https://www.youtube.com/watch?v=TyMUY2CDrjc&list=RDsB-S5LBU1eA&index=2",
        "hey daddy": "https://www.youtube.com/watch?v=pD8mxge6kek&list=RDsB-S5LBU1eA&index=4",
        "pyaar hota kayi baar hai": "https://www.youtube.com/watch?v=2yeRRm9AIxI&list=RDsB-S5LBU1eA&index=5",
        "mere nishan": "https://www.youtube.com/watch?v=wqaF_so8RJs&list=RDsB-S5LBU1eA&index=6",
        "this side of paradise": "https://www.youtube.com/watch?v=XgNc8iELq0c",
        "beauty and a beat": "https://www.youtube.com/watch?v=Ys7-6_t7OEQ&list=RDYs7-6_t7OEQ&start_radio=1&rv=f3AZBve64DE",
        "eenie meenie": "https://www.youtube.com/watch?v=prmmCg5bKxA&list=RDYs7-6_t7OEQ&index=2",
        "baby": "https://www.youtube.com/watch?v=kffacxfA7G4&list=RDYs7-6_t7OEQ&index=7",
        "the one that got away": "https://www.youtube.com/watch?v=Ahha3Cqe_fk&list=RDYs7-6_t7OEQ&index=8",
        "stay": "https://www.youtube.com/watch?v=kTJczUoc26U&list=RDYs7-6_t7OEQ&index=5",
        "payphone": "https://www.youtube.com/watch?v=KRaWnd3LJfs&list=RDYs7-6_t7OEQ&index=10",
        "attention": "https://www.youtube.com/watch?v=nfs8NYg7yQM&list=RDYs7-6_t7OEQ&index=12",
        "the man who can't be moved": "https://www.youtube.com/watch?v=gS9o1FAszdk",
        "meri laila": "https://www.youtube.com/watch?v=ThPinA3THas",
        "galat baat hai": "https://www.youtube.com/watch?v=MwVobP0QFic",
        "line without a hook": "https://www.youtube.com/watch?v=vfnAYipqj1k",
        "give me some sunshine": "https://www.youtube.com/watch?v=lbCRtrrMvSw",
        "sapphire": "https://www.youtube.com/watch?v=JgDNFQ2RaLQ",
        "night changes": "https://www.youtube.com/watch?v=syFZfO_wfMQ",
        "gone gone gone": "https://www.youtube.com/watch?v=oozQ4yV__Vw",
        "blue": "https://www.youtube.com/watch?v=IpFX2vq8HKw",
        "darkhaast": "https://www.youtube.com/watch?v=LMnJp_dSdnw",
        "diet mountain dew": "https://www.youtube.com/watch?v=sEetXo3R-aM",
        "let down": "https://www.youtube.com/watch?v=ZVgHPSyEIqk",
        "i think they call this love": "https://www.youtube.com/watch?v=S3rdEQ0M7n4",
        "co2": "https://www.youtube.com/watch?v=U2SVCCENLjE",
        "alag aasmaan": "https://www.youtube.com/watch?v=vA86QFrXoho",
        "kun faya kun": "https://www.youtube.com/watch?v=T94PHkuydcw",
        "tum se hi": "https://www.youtube.com/watch?v=Cb6wuzOurPc",
        "rang jo lagyo": "https://www.youtube.com/watch?v=2vmMcIRNGLI&list=RDGMEMPipJmhsMq3GHGrfqf4WIqA&start_radio=1&rv=Cb6wuzOurPc",
        "senorita": "https://www.youtube.com/watch?v=yDv0WSgXJVg&list=RDGMEMPipJmhsMq3GHGrfqf4WIqA&index=4",
        "illahi": "https://www.youtube.com/watch?v=6w67NOaRe-w&list=RDGMEMPipJmhsMq3GHGrfqf4WIqA&index=12",
        "samjhawan": "https://www.youtube.com/watch?v=wO5j3lv_9Fs&list=RDGMEMPipJmhsMq3GHGrfqf4WIqA&index=13",
        "kabira": "https://www.youtube.com/watch?v=jHNNMj5bNQw&list=RDGMEMPipJmhsMq3GHGrfqf4WIqA&index=17",
        "yeh fitoor mera": "https://www.youtube.com/watch?v=Zkqhiil2kSo",
        "aaoge tum kabhi": "https://www.youtube.com/watch?v=i96UO8-GFvw",
        "choo lo": "https://www.youtube.com/watch?v=opwZ_PJ-F_E",
        "paaro": "https://www.youtube.com/watch?v=DxsDekHDKXo",
        "bulleya": "https://www.youtube.com/watch?v=_51KXfwcPMs",
        "channa mereya": "https://www.youtube.com/watch?v=284Ov7ysmfA",
        "every breath you take": "https://www.youtube.com/watch?v=iOT_zuDHvVk",
        "we don't talk anymore": "https://www.youtube.com/watch?v=3AtDnEC4zak",
        "end of beginning": "https://www.youtube.com/watch?v=xy3AcmW0lrQ",
        "until i found you": "https://www.youtube.com/watch?v=GxldQ9eX2wo",
        "i wanna be yours": "https://www.youtube.com/watch?v=nyuo9-OjNNg",
        "heat waves": "https://www.youtube.com/watch?v=mRD0-GxqHVo",
        "7 years": "https://www.youtube.com/watch?v=LHCob76kigA",
        "somewhere only we know": "https://www.youtube.com/watch?v=Oextk-If8HQ"
        }